version: '3'

services:
  mysql:
    image: "sonsonson110/kien-truc-thiet-ke-final:mysqlv3"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  frontend:
    image: "sonsonson110/kien-truc-thiet-ke-final:frontendv3"
    stdin_open: true

  apigateway:
    depends_on:
      - userservice
      - resellerservice
      - productservice
      - frontend
    image: "sonsonson110/kien-truc-thiet-ke-final:apigatewayv3"
    restart: always
    ports:
      - "3050:80"


  userservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:userservicev3"
    # in case mysql not created
    restart: on-failure
    # keep open terminal
    stdin_open: true
    tty: true

  resellerservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:resellerservicev3"
    restart: on-failure
    stdin_open: true
    tty: true

  productservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:productservicev3"
    restart: on-failure
    stdin_open: true
    tty: true

# create persistence volumes on host for mysql
volumes:
  db: