version: '1'

services:
  mysql:
    image: "sonsonson110/kien-truc-thiet-ke-final:mysqlv1"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  frontend:
    image: "sonsonson110/kien-truc-thiet-ke-final:frontendv1"
    stdin_open: true

  apigateway:
    depends_on:
      - userservice
      - resellerservice
      - supplierservice
      - productservice
      - frontend
    image: "sonsonson110/kien-truc-thiet-ke-final:apigatewayv1"
    restart: always
    ports:
      - "3050:80"


  userservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:userservicev1"
    # in case mysql not created
    restart: on-failure
    # keep open terminal
    stdin_open: true
    tty: true
    # ports:
    #   - 8080:8080

  resellerservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:resellerservicev1"
    restart: on-failure
    stdin_open: true
    tty: true
    # ports:
    #   - 8081:8080

  supplierservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:supplierservicev1"
    restart: on-failure
    stdin_open: true
    tty: true
    # ports:
    #   - 8082:8080

  productservice:
    depends_on:
      - mysql
    image: "sonsonson110/kien-truc-thiet-ke-final:productservicev1"
    restart: on-failure
    stdin_open: true
    tty: true
    # ports:
    #   - 8083:8080

# create persistence volumes on host for mysql
volumes:
  db: