apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
      app: productservice
      tier: backend
  ports:
    - protocol: TCP
      port: 8080
  # type: ClusterIp by default, only accessible in k8s virtual network